### ISSUE TITLE
Pretty cool

### ISSUE THREAD

**Issue by mitar** [pubkey/event-reduce#2]
This is really cool. It reminds me of https://github.com/mit-pdos/noria a bit.

**Comment by mitar** [comment]
Also to list to related work: https://github.com/hasura/graphql-engine/blob/master/architecture/live-queries.md

**Comment by pubkey** [comment]
@mitar Thank you for posting this, I didn't know noria. Before creating event-reduce I checked for over two years if something similar already exists but could not find any reuseable implementation. So strange that I never stumpled over the hasura live queries docs.

I think the big difference between event-reduce and materialized views is the cost at write time and how it scales. If you have many users all observing different queries, you cannot create so many views because it would break your server on writes.

**Comment by mitar** [comment]
Yes, I am collecting [a list of related projects here](https://github.com/tozd/node-reactive-postgres/issues/7).

> I think the big difference between event-reduce and materialized views is the cost at write time and how it scales. If you have many users all observing different queries, you cannot create so many views because it would break your server on writes.

I think this really depends how it is implemented. I think incremental materialized view maintenance is very similar to what you have in event reduce, no? See more information about that in current attempt to add that to [PostgreSQL](https://wiki.postgresql.org/wiki/Incremental_View_Maintenance).

**Comment by pubkey** [comment]
Maybe I am misunderstanding it. 
Nice list you have there, give me some time to suck up the information.

**Comment by pubkey** [comment]
Closing this, I have read all the other sources. I think all of these solve slightly different problems but let's see what the future brings.
